---
- name: Check disk size and etc..
  hosts: localhost
  tasks:
    - name: Execure the DF -H command
      register: dfout
      command: "df -h"
      ignore_errors: yes
      
    - debug: msg="{{ dfout.stdout_lines }}"
