---
- name: Check hostname, version and distr.
  hosts: localhost
  tasks:
    - name: Execure the UNAME command
      command: "uname -a"
      ignore_errors: yes
      register: uname_result        
     - debug: msg="{{ uname_result.stdout }}"
